site_name: Prokofiev Sonatas
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  icon:
    logo: fontawesome/solid/p
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# plugins:
#   - glightbox:
#       touchNavigation: true
#       loop: false
#       effect: zoom
#       slide_effect: slide
#       width: 100%
#       height: auto
#       zoomable: true
#       draggable: true
#       skip_classes:
#         - custom-skip-class-name
#       auto_caption: false
#       caption_position: bottom
#       background: white
#       shadow: true
#       manual: false
# - autorefs:
#     # This will automatically generate navigation from the docs directory
#     auto_nav: true
extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/felix-fung-m9384/

copyright: Copyright &copy; 2024 Felix Fung
